#server:
#  port: 20001

  #本地环境
config:
  db:
    ip: 127.0.0.1
    port: 3306
    username: root
    password: root
  redis:
    ip: 127.0.0.1
    port: 6379
    password: root
#    password: 123456

spring:
  application:
    name: meeting
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${config.db.ip}:${config.db.port}/meeting?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: ${config.db.username}
    password: ${config.db.password}
  redis:
    host: ${config.redis.ip}
    port: ${config.redis.port}
    password: ${config.redis.password}
    jedis:
      pool:
        max-wait: 10000
        max-idle: 200
    timeout: 10000
    block-when-exhausted: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB

#logging:
#  config: classpath:logback-spring.xml


#mybatis-plus:
#  config-location: classpath:mapper/*.xml
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.saic.meeting.model.entity
#  configuration:
#    map-underscore-to-camel-case: true
