#server:
#  port: 20002

  #办公室环境
config:
  db:
    ip: 192.168.10.236
    port: 3306
    username: root
    password: root@123456
  redis:
    ip: 192.168.10.236
    port: 6388
    password: java123!
  #    port: 6379
  #    password: "ENC(oIc7DEw1pyKe4RfYEjdInYhZMKRFQVZc)"
  es:
    ip: 192.168.10.236
    port: 9300
    clusterName: elasticsearch

#当前使用配置配置
  #    url: jdbc:mysql://${config.db.ip}:${config.db.port}/new_test?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
spring:
  profiles: pre
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${config.db.ip}:${config.db.port}/service_center?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: ${config.db.username}
    password: ${config.db.password}
  redis:
    host: ${config.redis.ip}
    port: ${config.redis.port}
    password: ${config.redis.password}
    jedis:
      pool:
        max-wait: 10000
        max-idle: 200
    timeout: 10000
    block-when-exhausted: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB
  #心跳检查 路径 默认 RestClientProperties类 http://localhost:9200
  elasticsearch:
    rest:
      uris: http://${config.es.ip}:9200 #["http://192.168.10.236:9200"]

  mail:
    host: smtp.163.com
    username: 15021361926@163.com
    password: MHLHUOPJTVHPPBOH
    sendUser: yjp
    to: 1434300254@qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: UTF-8
    port: 465

#系统设置
system:
  email:
    sendAddress: 15021361926@163.com
    sendUser: yjp
    sendPwd: jinping.yan
    errorAddress: 1434300254@qq.com
    errorTitle: 系统异常
  sms:
    accessKeyId: LTAI4GFtPoFubHRiXPug7b3Z
    accessKeySecret: JsEcknUUS8Bq2iiJtSvcnPo2IOEArG
    signName: 生日祝福
    domain: dysmsapi.aliyuncs.com
    version: 2017-05-25
    action: SendSms
    regionId: default
  base:
    tokenMax: 5
    tokenValidDay: 7

file:
  fileTmpPath: D:/tmp2

elasticsearch:
  host: ${config.es.ip}
  port: ${config.es.port}
  clusterName: ${config.es.clusterName}

logging:
  config: classpath:logback-spring.xml