server:
  port: 20000
  servlet:
    context-path: /erm
  max-http-header-size: 10240
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    max-connections: 10000

#多开发环境配置 2020/04/23
spring:
  profiles:
    active: dev
